version: '2'

services:
    auth:
        build: ./auth
        container_name: auth.tdc
        restart: unless-stopped
        ports:
            - "81:5000"
        volumes:
            - /home/yreis/projects/flask-restful-microservices/auth:/usr/src/app
        networks:
            - example_net

    user:
        build: ./user
        restart: unless-stopped
        container_name: user.tdc
        ports:
            - "82:5000"
        volumes:
            - /home/yreis/projects/flask-restful-microservices/user:/usr/src/app
        networks:
            - example_net

networks:
    example_net:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 172.19.0.0/24
              gateway: 172.19.0.1
