version: '2'

services:
    auth:
        build: ./auth
        container_name: auth.tdc
        restart: unless-stopped
        ports:
            - "81:80"
        environment:
            - DB_USER=root
            - DB_PASS=tdc
            - DB_HOST=db.tdc
            - DB_NAME=tdc
            - PREFIX=Bearer
            - SECRET=tdc
        volumes:
            - "./auth:/usr/src/app"
        depends_on:
            - db
        networks:
            - example_net

    user:
        build: ./user
        container_name: user.tdc
        restart: unless-stopped
        ports:
            - "82:80"
        environment:
            - DB_USER=root
            - DB_PASS=tdc
            - DB_HOST=db.tdc
            - DB_NAME=tdc
            - PREFIX=Bearer
            - SECRET=tdc
        volumes:
            - "./user:/usr/src/app"
        depends_on:
            - db
        networks:
            - example_net

    db:
        image: mysql:8.0
        container_name: db.tdc
        restart: unless-stopped
        volumes:
            - "./mysql-data:/var/lib/mysql"
        environment:
            - MYSQL_ROOT_PASSWORD=tdc
        ports:
            - "3306:3306"
        networks:
            - example_net

networks:
    example_net:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 172.19.0.0/24
              gateway: 172.19.0.1
